---
encoding: utf-8
title: JSON-GUI
timezone: Europe/Amsterdam
collections:
  client_collection:
    title: Pagina's inhoud
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  parts_min:
    title: Parts
    output: true
sass:
  compressed: true
volledige-titel: JSON Gui
url: https://json-gui.site
enforce_ssl: json-gui.site
keywords: JSON, GUI, interface
google_analytics: UA-112439526-2
description: A JSON Viewer and editor for visually editing JSON files. Supported file types for importing and exporting are CSV, YAML, XML etc. You are also able to generate JSON patches (RFC6902).
github_username: LesterGallagher
youtube_username: 9Wereld
twitter_username: esstudio_site
social:
  name: Esstudio
  links:
    - https://twitter.com/esstudio_site
    - https://github.com/LesterGallagher
rss: Blog
rss_url: https://esstudio.site/feed.xml
rss_html_url: https://esstudio.site/blog
markdown: kramdown
theme: minima
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.png
      width: 192
      height: 192
      lang: en
      title: JSON GUI
twitter:
  username: esstudio_site
  card: summary
plugins: 
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: info@esstudio.site
  twitter: esstudio_site
designer:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Designer
  email: info@esstudio.site
  twitter: esstudio_site
google_analytics: UA-90014538-3
